kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp

spec:
  replicas: 2
  selector:
     matchLabels:
        env: qa
  
  template:
    metadata:
      name: myapp
      labels:
        env: qa

    spec:
      containers:
          - name: c1
            image: kshiteejjain84/myjdk
            ports:
              - containerPort: 8080
