pipeline{
  agent none
  options {
    skipDefaultCheckout()
  }
stages {
  stage('clone git repo to cutom location') {
    agent {
    label 'built-in'
    }
  steps {
    dir('/mnt/kubernetes') {
      sh 'rm -rf *'
      checkout scm
    }
  }  
  }
  stage('build custom docker image') {
  agent {
    label 'built-in'
  }
  steps {
    dir('/mnt/kubernetes') {
      sh ' sudo docker build -t kshiteejjain84/myjdk:latest .'
    }
  }
  }
  stage('push docker image to docker registry') {
  agent {
    label 'built-in'
  }
   steps {
     dir('/mnt/kubernetes') {
       sh '''
          sudo docker login -u kshiteejjain84 -p KDSgroup@131120
          sudo docker push kshiteejjain84/myjdk:latest
          sudo docker logout
          '''
     }
   }
  }
  stage('deploy pod and services') {
    agent {
      label 'built-in'
    }
  steps {
    dir('/mnt/kubernetes') {
      sh '''
         sudo kubectl apply -f deployment.yaml
         sudo kubectl apply -f service.yaml
         '''
    }
  }
  }
}
}
