pipeline{
  agent none
  options {
    skipDefaultCheckout()
  }
stages {
  stage('clone git repo to cutom location') {
    agent {
    label 'built-in'
    }
  steps {
    dir('/mnt/kubernetes') {
      sh 'rm -rf *'
      checkout scm
    }
  }  
  }
  stage('build custom docker image') {
  agent {
    label 'built-in'
  }
  steps {
    dir('/mnt/kubernetes') {
      sh ' docker build -t kshiteejjain84/myapp
    }
  }
  }
}
}
